### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by JKrag** [Praqma/gradle-plugin-bootstrap#1]
If this project is really intended for people to copy and re-use as a base for their own plugins, as stated in the blog post, then it should probably have a license that specifically allows this.
I think [MIT](https://choosealicense.com/licenses/mit/) should do the job (Caveat lector).

**Comment by buep** [comment]
Good catch Jan.

It have to be MIT though. That is our decison.

**Comment by praqma-thi** [comment]
MIT license added, thanks Jan.
