### ISSUE TITLE
Call a external plugin from my custom plugin

### ISSUE THREAD

**Issue by fabiodcorreia** [Praqma/gradle-plugin-bootstrap#3]
Hi,

Great bootstrap project, but I'm having a problem I want to use an external plugin from my custom plugin, in my case is the plugin 'org.ajoberstar.grgit'.

I have it on my build.gradle but I'm not sure if it's necessary there and then I also added 

```java
public void apply(Project project) {
    project.plugins.apply('org.ajoberstar.grgit')
    WebUIModule.load(project)
};
```
and I want to call it on my WebUIModule task that I define inside the load, but when I run it on the tests it always says 

```
 Plugin with id 'org.ajoberstar.grgit' not found.
```

I also tried to put the version but I get the same problem

**Comment by fabiodcorreia** [comment]
Found the solution

**Comment by claym** [comment]
Care to share it?

**Comment by fabiodcorreia** [comment]
> Care to share it?

I end up not calling the plugin but importing the Java lib used on the plugin, in my case I used the JGit java library.
