### ISSUE TITLE
Executing tasks?

### ISSUE THREAD

**Issue by claym** [Praqma/gradle-plugin-bootstrap#4]
What's the proper method for executing the helloTarget and helloWorld tasks?

```gradlew helloTarget``` does not register as a task:

* What went wrong:
Task 'helloTarget' not found in root project 'demo'.

**Comment by praqma-thi** [comment]
What does your `build.gradle` script look like?
Just applying the plugin should be enough, either as it's published on [plugins.gradle.org](https://plugins.gradle.org/plugin/com.praqma.demo.DemoPlugin) or however you're distributing your fork.

```
$ cat build.gradle
───────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: build.gradle
───────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ plugins {
   2   │     id "com.praqma.demo.DemoPlugin" version "1.0.0"
   3   │ }
───────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

$ ./gradlew helloWorld
> Task :helloWorld
Hello, world!

BUILD SUCCESSFUL in 0s
1 actionable task: 1 executed
```

Note that this repository is the plugin itself, and as the plugin doesn't apply itself in its `build.gradle` file, it doesn't actually have the `helloWorld` and `helloTarget` tasks.

**Comment by claym** [comment]
> id "com.praqma.demo.DemoPlugin" version "1.0.0"

yep, that was it. Forgot it was a bootstrap, not a fully working plugin. Sorry about the dumb question!

**Comment by praqma-thi** [comment]
It's a functional plugin, it just doesn't apply itself, so it can't run its own tasks. :slightly_smiling_face: 
Regardless, glad I could help.

**Comment by claym** [comment]
Just a follow up - i'm working on customizing this and was wondering if it's possible to actually make run it's own tasks?

do you have to publish first and then apply?

i'm just trying to figure out what the optimal development workflow for this would be.

Thanks!

**Comment by praqma-thi** [comment]
I tried this as well. AFAIK, for the plugin's `build.gradle` to use its own tasks and configuration, you have to publish it first and then apply it. It works, but it's a bit awkward.

If you find a smarter way of doing it, feel free to drop it in here. I'm curious myself. :slightly_smiling_face:

**Comment by claym** [comment]
hahah yeah it's a little awkward. not this project's fault, i think it's 100% a gradle thing
